os:
  - linux
sudo: no
addons:
  apt:
    packages:
    - python
    - libgc-dev
    - libgmp-dev
    - libgtk-3-dev
    - libev-dev
    - libjansson-dev
    - ocaml
  
before_install:
  - date
  - cat /proc/cpuinfo
  # Install pkgs
  - ${TRAVIS_BUILD_DIR}/travis-ci/installpkg.sh
  - cd ${HOME}
  - mkdir pkg
  - export CFLAGS="-Wno-unused-but-set-variable"
  - (cd json-c-0.12 && ./configure --prefix=${HOME}/pkg && make all && make install)
  - cd ${HOME}
  # Download ATS2
  - git clone git://git.code.sf.net/p/ats2-lang/code ATS2-srcfrg
  # Download my ATS2 Contrib
  - git clone https://github.com/wdblair/ATS-Postiats-Contrib my-ats2-contrib
  - export PATSHOMERELOC=${HOME}/my-ats2-contrib
  - export PKG_CONFIG_PATH=${HOME}/pkg/lib/pkgconfig/
  - export LD_LIBRARY_PATH=${HOME}/pkg/lib/
  - export C_INCLUDE_PATH=${HOME}/pkg/include/
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.4.1/z3-4.4.1-x64-ubuntu-14.04.zip
  - unzip z3-4.4.1-x64-ubuntu-14.04.zip
  - (cd z3-4.4.1-x64-ubuntu-14.04 && cp bin/lib* ${HOME}/pkg/lib/ && cp include/* ${HOME/pkg/include/})
  
script:
  # Building ATS2
  - export PATSHOME=${HOME}/ATS2-srcfrg
  - export PATH=${PATH}:${PATSHOME}/bin
  - (cd ${PATSHOME} && ./configure && make all)
  - export PATH=${HOME}/bin:${PATH}
  - (cd my-ats2-contrib/projects/MEDIUM/ATS-extsolve && make)

after_script:
  - date
