#!/bin/bash
#
# Build a self-contained C-source release of the Overture compiler,
# in the spirit of ATS2's own CBOOT distribution: patsopt generates
# portable C for every module, and the transitive closure of quoted
# #include references (runtime headers and .cats fragments) is
# copied alongside, so the result builds with nothing but a C
# toolchain -- no ATS compiler required.
#
# Usage: share/mkrelease.sh   (from the repository root)
#   PATSHOME may be set; it defaults to the vendored toolchain.
#

set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
export PATSHOME="${PATSHOME:-$root/ATS2-Postiats-int-0.4.2}"
export PATH="$PATSHOME/bin:$PATH"

version=$(sed -n 's/#define OVERTURE_VERSION "\(.*\)"/\1/p' \
  "$root/src/overture_main.dats")
name="overture-${version}-src-c"
dist="$root/dist"
out="$dist/$name"

echo "mkrelease: assembling $name"
rm -rf "$out" && mkdir -p "$out/c" "$out/runtime"

# ---- 1. portable C for every Overture module ----

cd "$root/src"
for f in *.sats; do
  patsopt -o "$out/c/${f%.sats}_sats.c" -s "$f"
done
for f in *.dats; do
  patsopt -o "$out/c/${f%.dats}_dats.c" -d "$f"
done

# ---- 2. transitive closure of quoted includes ----
#
# References of the form pats_ccomp_* resolve in ccomp/runtime and
# land flat in runtime/; path-shaped references (prelude/CATS/...,
# libats/...) resolve at the PATSHOME root and keep their layout.
# Generated C sometimes wraps #include over a backslash
# continuation, so join those before scanning.

scan_includes () {
  awk '{ if (sub(/\\$/, "")) printf "%s", $0; else print }' "$@" \
    | grep '#include "' | sed 's/.*"\(.*\)".*/\1/' | sort -u
}

worklist=$(scan_includes "$out"/c/*.c)

copied=""
while [ -n "$worklist" ]; do
  next=""
  for ref in $worklist; do
    case " $copied " in *" $ref "*) continue ;; esac
    copied="$copied $ref"
    case "$ref" in
      pats_ccomp_*)
        src="$PATSHOME/ccomp/runtime/$ref"; dst="$out/runtime/$ref" ;;
      */*)
        src="$PATSHOME/$ref"; dst="$out/$ref" ;;
      *)
        # bare non-runtime name: resolved by the C compiler elsewhere
        continue ;;
    esac
    if [ ! -f "$src" ]; then
      echo "mkrelease: warning: cannot resolve include [$ref]" >&2
      continue
    fi
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    more=$(scan_includes "$dst" || true)
    next="$next $more"
  done
  worklist=$(printf '%s\n' $next | sort -u)
done

# ---- 3. build scaffolding for the release ----

cp "$root/LICENSE" "$out/LICENSE"

cat > "$out/Makefile" <<'EOF'
#
# Building the Overture compiler from pregenerated C sources.
# Requires only a C toolchain; the ATS compiler is not needed.
#

CC ?= cc
CFLAGS ?= -O2

OVERTURE_CFLAGS = \
  -std=c99 -D_XOPEN_SOURCE -D_GNU_SOURCE \
  -DATS_MEMALLOC_LIBC -I. -Iruntime

SRCS := $(wildcard c/*.c)
OBJS := $(SRCS:.c=.o)

overture: $(OBJS)
	$(CC) -o $@ $(OBJS)

c/%.o: c/%.c
	$(CC) $(OVERTURE_CFLAGS) $(CFLAGS) -c -o $@ $<

PREFIX ?= /usr/local
install: overture
	install -d $(DESTDIR)$(PREFIX)/bin
	install overture $(DESTDIR)$(PREFIX)/bin/overture

clean:
	rm -f $(OBJS) overture

.PHONY: install clean
EOF

cat > "$out/README" <<EOF
Overture $version -- C-source release

    https://github.com/wdblair/overture

This directory contains the Overture compiler as portable C,
pregenerated by the ATS2 toolchain (in the manner of ATS2's own
CBOOT bootstrap sources). Building requires only a C compiler:

    make            # produces ./overture
    make install    # PREFIX=/usr/local by default

    overture --typecheck program.ovt

The full pipeline is self-contained: overture --codegen (or
--codegen=c) emits a C harness buildable with the same C toolchain:

    ./overture --typecheck --codegen program.ovt
    cc -std=c99 -O2 -o program program_gen.c program_stubs.c

(--codegen=ats emits an ATS2 harness instead, for trees where the
ATS2 toolchain is available.)

Overture is licensed under the GNU GPL, version 3 or later (see
LICENSE), matching ATS2/Postiats, from which the bundled runtime/
and prelude/libats fragments originate (http://www.ats-lang.org/).
EOF

# ---- 4. sanity: the release must build and run on its own ----

echo "mkrelease: verifying the release builds without ATS"
( cd "$out" && env -u PATSHOME make -s overture )
"$out/overture" --version
"$out/overture" --typecheck "$root/tests/pos/sampling.ovt"
( cd "$out" && make -s clean )

# ---- 5. tarball ----

tar czf "$dist/$name.tgz" -C "$dist" "$name"
echo "mkrelease: wrote dist/$name.tgz"
